### ISSUE TITLE
Ordered test support in Run Functional Tests task

### ISSUE THREAD

**Issue by endrton** [Microsoft/vsts-tasks#1923]
I'm on an onpromise TFS 2015 with update 2. I have a release definition which contains several environments and one of them looks like this:
- Windows Machine File Copy  (deploys the assemblies from a build)
- Visual Studio Test Agent Deployment
- Run Functional Tests
  Test Selection: Test Assembly
  Test Assembly: *_\_XYZ.orderedtest (XYZ is the proper name of the ordered test file but it does not matter at this point).

Deploying to this environment results in the following error:
## [warning]DistributedTests: Test run aborted. Test run id: 278798

I'm wondering whether the ordered test is supported in this task or i have setup something wrong.
Any thoughts?

**Comment by brettjacobson** [comment]
My company has faced the same problem.  I've read that ordered tests are not supported, then I read they are, but experience has shown that they are not.  This particular thread claims it works: https://social.msdn.microsoft.com/Forums/en-US/711c1f98-2d58-4b9b-805b-204ce6cc4d45/how-to-use-vnext-build-ordered-tests-distribute-test-collect-results?forum=tfsbuild

**Comment by nigurr** [comment]
@atinb please update whether we support this feature?

**Comment by atinb** [comment]
Unfortunately, Ordered tests are currently not supported with the Run Functional Test task. You can use the Visual Studio test task for running Ordered tests. Thanks!

**Comment by atinb** [comment]
We have identified a workaround that will enable you to run Ordered tests.
Please copy this file to the same location on the test agent machine: Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow\Extensions\Microsoft.VisualStudio.TestPlatform.Extensions.OrderedTestAdapter.dll
Once this is done, you should be able to trigger ordered tests on the Agent machines. Thanks!

**Comment by zmckinnon** [comment]
We tried this at our organization and IT WORKS.  Thanks @atinb.

**Comment by sailajacharan** [comment]
We tried this at our organization, it worked perfectly.  Thanks @atinb.

**Comment by sailajacharan** [comment]
HI @atinb, we implemented above work around and were very happy to see ordered tests run successfully. But we now are in to an issue where the test results generated from TFS build
 show passed while an individual test in the ordered test suite actually failed.

![pimsbuild](https://cloud.githubusercontent.com/assets/20461864/18143759/0d07b23a-6f89-11e6-9f42-cf5de4ecbcc1.PNG)

**Comment by Abhishek-Heggere** [comment]
I see the same discrepancy, dug into it a bit more. Found out that if any tests throw an exception, the test outcome becomes green. Then on it always remains green regardless.

**Comment by ampetrushenko** [comment]
Hi!
After we have implemented ordered tests we can see only "Main" test result in TFS Web, but to see test results of individual tests in the ordered test suite we need to download the *.trx file and open it in Visual Studio.

Maybe anybody know how to display test results of individual test in the ordered test suite in TFS Web, without downloading *.trx

Thank you in advance

**Comment by allendm-msft** [comment]
@ampetrushenko Currently this is the only option.

**Comment by PriyaGopi** [comment]
@atinb or Any one else who implemented the orderedtest in TFS successfully.
Can you please share the Test Assembly syntax alone, plz ? It's an emergency for me.

**Comment by sailajacharan** [comment]
@PriyaGopi - Test Assembly syntax: CodedUI Build Artifacts\Project1.orderedtest;CodedUI Build Artifacts\Project2.orderedtest

let me know if u still cant figure it out.

**Comment by PriyaGopi** [comment]
Hi sailajacharan,
My test assemble is : Test Assembly                   **\*SolutionName*.dll
And my orderedtest name is : Sample.orderedtest

I updated the Test Assemble like this : **\*SolutionName*.dll\Sample.orderedtest
And set the "TestFilterCriteria" to empty
But it failed, giving the error : 

**Error : Invalid source specification '**\*SolutionName*.dll\Sample.orderedtest'. Provide correct source specification and try again.

##[error]The test run was aborted, failing the task.**

Please give the correct syntax... 

My requirement is actually : I'm using specflow & I need to order the execution of testcase. 
As researched that specflow scenarios can take tags called TestCategory to filter out the testcase.
Similarly, I saw something like "Priority", but I don't know how to set the Priority.
To set TestCategory the syntax is @Test_Category_Name. 
Similarly, is there any syntax for this ?

Also in TFS Continuous Integration TestResult's table, I see a column called "Priority" with no values for all rows.

If either need to set the Priority Attribute to all the Scenarios , or use the OrderedTest to execute.
Any one solution would do for me?

Is my explanation clear enough? Sorry for the lengthy explanation ..... :)

**Comment by PriyaGopi** [comment]
Hi guys! Any update on my issue.

**Comment by PriyaGopi** [comment]
Hi,

I even tried to prefix the testccase No. with 1_TCNo.   2_TCNo.   3_TCNo.  4_TCNo.  5_TCNo.
but  still no use, it is running on its own order, but similar order all the time as below :
5, 1, 2, 3, 4
since the 5th Test case's data is dependent from Testcase 4, Testcase 5 will always fail saying 'Data not found in the ComboBox'.

Someone kindly help me to order the execution/flow of the testcases.

Thanks in advance.

**Comment by Abhishek-Heggere** [comment]
I have the ordered test working and my setting look like this -
Test Drop Location = D:\Builds\MyBuild\Tests 
Test Selection = Test Assembly
Test Assembly = **\my.vnext.orderedtest
Test Filter Criteria = <Empty>

1. Just giving the orderedtest file name should be ok :
   "**\Sample.orderedtest"  instead of  "*\SolutionName*.dll\Sample.orderedtest"  
2. Test the pattern on vstest.console.exe, if it works there then it should work from build definition.

**Comment by atinb** [comment]
@PriyaGopi Did the suggestion above help or are you still facing issues?

**Comment by PriyaGopi** [comment]
Hi, Abhishek/atinb

I treid the solution, but I got the below error.

DistributedTests: Error : Test run directory 'C:\Deploy' does not contain any assemblies that match the specified criteria: '**\Sample.orderedtest'. Verify that the test run directory contains the target assemblies and the source filter is correct.
DistributedTests: Test run aborted. Test run id: 12345
The test run was aborted, failing the task.

I verified the file "Microsoft.VisualStudio.QualityTools.CodedUITestFramework.dll"  & the "Sample.orderedtest" are placed in the 'C:\Deploy' folder.

I'm wondering whether I'm missing any settings of some kind....

Appreciate your support.

Thanks...

**Comment by Abhishek-Heggere** [comment]
I have seen this issue before, couple of things to check -
1. Open the orderedtest in notepad and verify the 'storage' property points to the right location of the unit test assembly.
2. Before you run the test through the build definition make sure that the orderedtest can be executed via the vstest.console.exe on the target machine.

**Comment by PriyaGopi** [comment]
1. 'storage' property correctly points to the build dll's only.
2. Orderedtest executed via vstest.console.exe successfully, see attached screenshot.

![vs test console](https://cloud.githubusercontent.com/assets/23239207/20093350/5d3857d6-a5c2-11e6-9d36-e9269fcb0195.png)

**Comment by Blinkk** [comment]
@atinb I tried your solution by copying the OrderedTestAdapter.dll to the same directory as the test assemblies on the test machine, but I am still unable to run an ordered test. Is there any update on this?

**Comment by acesiddhu** [comment]
@Blinkk did you copy the dll to c:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow\Extensions\Microsoft.VisualStudio.TestPlatform.Extensions.OrderedTestAdapter.dll? or you just copied it to test folder. can you try putting the dll at Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow\Extensions\Microsoft.VisualStudio.TestPlatform.Extensions.OrderedTestAdapter.dll and try again

**Comment by acesiddhu** [comment]
I am closing this issue. Let me know if the above step didn't help

**Comment by choang76** [comment]
I'm having the same issue executing .orderedtest using vstest..console.exe from both command line and from TFS Functional Test task as others have described.  I have done:

1. copy the .dll to BOTH c:\deployment (where tests artifacts reside) and c:\progr...\ as others
2. execute vstest.console from commandline and tfs and still get tests not being discovered.

Any update on this issue?

**Comment by Nbhonrao** [comment]
i have used OrderedTest.orderedTest in tfs build. i am able to execute the test case properly but i would like to know that how to update the test case status in respective test suite in tfs

**Comment by snehalatamath** [comment]
> i have used OrderedTest.orderedTest in tfs build. i am able to execute the test case properly but i would like to know that how to update the test case status in respective test suite in tfs

Hi,
Can you please tell me how can I run orderedtest using tfs build? 

Thanks in advance
