### ISSUE TITLE
cURL Upload fails with wildcards since latest TFS update

### ISSUE THREAD

**Issue by k3flo** [Microsoft/vsts-tasks#2914]
Hi,

we are using a cUrl Upload task with the following configuration which worked till 19th October 2016:

![configuration correct](https://cloud.githubusercontent.com/assets/12381373/19602663/5dfb0adc-97ae-11e6-914a-852cdb203076.jpg)

Since yesterday, this build step fails with this error message:

![fail](https://cloud.githubusercontent.com/assets/12381373/19598225/f5652f7a-9799-11e6-9f3d-427fe6b541bf.jpg)

It seems like the '\' characters were trimmed away (see line 3).

What is wrong here?

regards

Florian

**Comment by dannylgreen** [comment]
Hello,

Confirming this issue, I am seeing the same thing with version 1.0.19.

**Comment by dannylgreen** [comment]
Hello,

If there is legitimate way to have a Task use a specific version I can't find it, but I was able to trick mine to use version 1.0.17 and get my release out.  On my build agent, in the BuildAgent\Tasks\cURLUploader folder, I renamed the 1.0.19 folder to xxx1.0.19, made a copy of the 1.0.17 folder and then renamed it to 1.0.19.

**Comment by yacaovsnc** [comment]
@k3flo @dannylgreen It appears there is an path issue (curl expecting forward slashes as path separator and normalized away Windows' path separators) introduced recently, possibly by a library update.  

A workaround to this issue is to specify the full path to the file that will be uploaded without any wildcard.  This way we don't attempt to search the file by pattern matching and curl can take Windows path as its '-T'  value.

@k3flo the build definition you posted looks different from the log you posted -- they are uploading different files.  The build definition you post should work as it is pointing to a file directly.

**Comment by k3flo** [comment]
@yacaovsnc I'm very sorry, I pasted the wrong image. I fixed the image so that the definition matches the log.

**Comment by yacaovsnc** [comment]
Thanks @k3flo, assuming your version number is v3.1.16_11010, you could potential unblock yourself by changing the input to:
`$(build.sources.directory)\labs.ETL\Docs\Release Notes\$(VersionNumber)_labs.Flow_Release_Notes.pdf`

I am looking at the root cause at the moment.  

Sorry about the trouble.

**Comment by yacaovsnc** [comment]
We have hotfixed this issue now.  Sorry it took awhile because of github.com was down today.  Please try again.

**Comment by sawpresto** [comment]
@yacaovsnc I'm using version 2.* in VSTS on a Hosted Windows agent (both VS2017 and Hosted) and it seems like I'm still getting the issue where in the logs it shows that it has removed all slashes and can't find the file at d:ar1aPartsUnlimitedARMTemplatesAppInsights.json only when doing a minimatch. I don't run into this error when running the Hosted Linux Preview. Here are the combinations I've tried:

- **/*.json
- **\*.json
- **\\*.json
- $(System.DefaultWorkingDirectory)/PartsUnlimited/ARMTemplates/**

Looking in the code, it looks like perhaps the isWin variable isn't used? Do you know how I can get the task working against multiple files? I'd prefer to not have to have a task for each file hard-coded.

**Comment by yacaovsnc** [comment]
I see the matching logic has [changed](https://github.com/Microsoft/vsts-tasks/commit/9e7cd2700b4aa9a698a5789645febc01e5a3305a#diff-b19fe201640a3e02d32b36843afe0c16) recently.   

I will route this to the right person to take a look.

**Comment by sawpresto** [comment]
Great, thank you! This is a bit time sensitive so if someone can take a look at this right away, I would appreciate it very much!!

**Comment by lkillgore** [comment]
Hi @sawpresto, thanks for pointing this issue out to us.  I was able to reproduce the issue, and we're working on a fix for it.  Sorry for the inconvenience.

**Comment by sawpresto** [comment]
Thanks, @lkillgore! Do you have an estimate of when the updated task will be released at earliest? Not sure if task updates fall within VSTS's release cycles.

**Comment by lkillgore** [comment]
@sawpresto, these tasks do fall within VSTS's release cycles, but we are eyeballing this for a hotfix outside of a normal release.  It's still early, so I don't want to say too much beyond that right now.  I'll try to see that this thread gets updated as decisions are made.

**Comment by lkillgore** [comment]
Hi @sawpresto, this issue is fixed in this PR: https://github.com/Microsoft/vsts-tasks/pull/6289.

Also, we are doing a hotfix release, which should be rolled out with changes to M129.  I don't know when your account will receive the fix (we do staged rollouts, and I don't know where your account lies in the rollout schedule).

If you want the fix now, you can update the task on your own account as described here: https://github.com/Microsoft/vsts-tasks/blob/master/docs/contribute.md, and here: https://github.com/Microsoft/tfs-cli/blob/master/docs/buildtasks.md (specifically, you're looking to 'upload' a task.)

**Comment by sawpresto** [comment]
Great, thanks, @lkillgore!

**Comment by madhurig** [comment]
@sawpresto: Can you let us know if the issue is resolved for you? We issued a hotfix last week.

**Comment by madhurig** [comment]
Closing since this issue has been fixed and deployed. Let us know if you still see issues.
