### ISSUE TITLE
Cannot use AppOffline rule on first deploy with virtual directory

### ISSUE THREAD

**Issue by mclark1129** [Microsoft/vsts-tasks#3046]
I believe this issue is similar to the one reported in Microsoft/vsts-rm-extensions#55.  When I try to deploy an application to a virtual directory for the first time, and I want to use the AppOffline rule, the task fails with the following error message:

> Error: Could not find a part of the path 'D:\home\site\wwwroot\v1\App_Offline.htm'.

If I run the task first without this rule, or manually create the virtual directory on the app service, the task succeeds.  I think that the task needs to manually create the directory if it doesn't already exist before running the msdeploy task so that the AppOffline rule will work.

**Comment by Ajay-MS** [comment]
@mclark1129 

Thanks for reporting this issue, we will fix it soon.

**Comment by Ajay-MS** [comment]
@mclark1129 

Creation of physical path corresponding to virtual application is a creation operation corresponding to webapp. Since main functionality of task is to do deployment as per spec we will not be able to include creation of physical path for virtual application as part of this task. **Azure App Service Deploy**  assumes website or virtual application(along with physical path should already exist). If in future there will be any task for webapp creation we will include physical path creation as part of that.

Second, Since physical path for a virtual application doesn't exist. It means deployment to virtual application is happening for first time. For first time deployment taking app_offline doesn't make much significance.

For now you can check following workarounds - 
1. Create physical path for virtual application from azure portal before deployment.
2. Don't select app_offline for first time deployment.

**Comment by mclark1129** [comment]
@Ajay-MS 

So why is it an acceptable fix for the IIS deployment task here?:

Microsoft/vsts-rm-extensions#54

This is basically the same exact thing, except for IIS and not Azure app.  I realize I can uncheck it the first time for initial deployment, I'm just trying to come up with a single deployment plan that works in every case, rather than a one off operation for initial deployments.

**Comment by Ajay-MS** [comment]
@mclark1129 

Yes you are right there should be single deployment plan. But let me explain you problem - 
For "IIS Web App Deployment" extension in vsts-rm-extension repo there are two tasks 
1.  **WinRm - IIS Web App Management** - function of this task is management operation like create, update.
2.  **WinRm - IIS Web App Deployment** - functionality of this task is to deploy webapp

So in above mentioned issue this has been fixed  in management operation as creation of physical path for a virtual application is management operation.

Now for azure, **Azure App Service Deploy** is only for deployment related operation. So in both of cases deployment task assumes that every resource it needs should already created. So here deployment plan is exactly same as **WinRm- IIS Web App Deployment**  task.

Only gap you are observing is because for azure a task corresponding to **WinRm - IIS Web App Management** is not there. Possible reason is frequency of creation and update operation is very less, so it could be easily performed manually from azure portal . If in future there will be any requirement for management operation. It will surely be there.

**Comment by Ajay-MS** [comment]
Closing as per discussion. Feel free to reopen if you have any question regarding it.

**Comment by sachinpachori** [comment]
Is this issue fixed. We are still getting the same issue.

**Comment by Ajay-MS** [comment]
@sachinpachori 

This issue has been already fixed.  Refer below link for fix
[Create physical path if doesn't exist](https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/AzureRmWebAppDeployment/azurermwebappdeployment.ts#L112)

Since you are still facing this issue please share your debug logs. Debug logs can be enabled by adding variable `System.debug`  with value `true`

**Comment by tolgabalci** [comment]
Still having the same issue here as well.  Brand new setup.

After hours of troubleshooting found this page and turned off "Take App Offline" the first deployment and it worked!  Then I turned it back on and redeployed an it worked!

**Comment by tolgabalci** [comment]
Here is a partial log showing the issue before I turned "Take App Offline" off:

`2018-01-10T02:25:15.1870966Z ##[debug]found 194 paths
2018-01-10T02:25:15.1871102Z ##[debug]applying include pattern
2018-01-10T02:25:15.1871256Z ##[debug]adjustedPattern: 'C:\vstsagent\A1\_work\r1\a\temp_web_package_8287370284012923\**/*.config'
2018-01-10T02:25:15.1914036Z ##[debug]8 matches
2018-01-10T02:25:15.1914286Z ##[debug]8 final results
2018-01-10T02:25:15.1915948Z ##[debug]Detected parameters.xml file - XML variable substitution
2018-01-10T02:25:15.1919105Z ##[debug]build.sourceBranchName=master
2018-01-10T02:25:15.1919299Z ##[debug]release.artifacts.BOB-5-NET45.buildNumber=20180110.6
2018-01-10T02:25:15.1919555Z ##[debug]system.workfolder=C:\vstsagent\A1\_work
2018-01-10T02:25:15.1919794Z ##[debug]MSDEPLOY_HTTP_USER_AGENT=VSTS_c0473092-f876-42cb-bf30-1bc1ca912f5f_release_2_14_14_1
2018-01-10T02:25:15.1920061Z ##[debug]release.artifacts.BOB-5-NET45.repository.id=2f786457-9c31-4683-9a03-92ff67c1dc03
2018-01-10T02:25:15.1920442Z ##[debug]agent.releaseDirectory=C:\vstsagent\A1\_work\r1\a
2018-01-10T02:25:15.1920789Z ##[debug]system.culture=en-US
2018-01-10T02:25:15.1920931Z ##[debug]release.artifacts.BOB-5-NET45.buildId=148
2018-01-10T02:25:15.1921079Z ##[debug]build.projectName=BOB
2018-01-10T02:25:15.1921221Z ##[debug]system.TeamFoundationServerUri=https://tolga.vsrm.visualstudio.com/
2018-01-10T02:25:15.1921369Z ##[debug]Parameters.VirtualPathForApplication=
2018-01-10T02:25:15.1921523Z ##[debug]release.environmentUri=vstfs:///ReleaseManagement/Environment/14
2018-01-10T02:25:15.1921944Z ##[debug]release.artifacts.BOB-5-NET45.definitionId=17
2018-01-10T02:25:15.1922092Z ##[debug]Parameters.CreateOrUpdateAppPoolForWebsite=true
2018-01-10T02:25:15.1922257Z ##[debug]release.artifacts.BOB-5-NET45.projectId=048c55e4-c19f-4503-bee7-da382fac2e92
2018-01-10T02:25:15.1922405Z ##[debug]release.releaseDescription=Triggered by BOB-5-NET45 20180110.6.
2018-01-10T02:25:15.1922564Z ##[debug]release.deploymentId=13
2018-01-10T02:25:15.1922706Z ##[debug]release.environments.Dev.status=InProgress
2018-01-10T02:25:15.1922860Z ##[debug]Parameters.IISDeploymentType=IISWebsite
2018-01-10T02:25:15.1923139Z ##[debug]agent.version=2.126.0
2018-01-10T02:25:15.1923309Z ##[debug]release.definitionId=2
2018-01-10T02:25:15.1923520Z ##[debug]release.artifacts.BOB-5-NET45.repository.name=BOB
2018-01-10T02:25:15.1923912Z ##[debug]release.deployment.requestedFor=Tolga Balci
2018-01-10T02:25:15.1926870Z ##[debug]Parameters.AppPoolNameForWebsite=supertim_localhost_pool
2018-01-10T02:25:15.1927303Z ##[debug]Parameters.WebsiteName=supertim.localhost
2018-01-10T02:25:15.1927661Z ##[debug]release.artifacts.BOB-5-NET45.sourceVersion=c06b3a39149d0e961dde89800fa77f5441f712be
2018-01-10T02:25:15.1928378Z ##[debug]system=deployment
2018-01-10T02:25:15.1928594Z ##[debug]agent.TempDirectory=C:\vstsagent\A1\_work\_temp
2018-01-10T02:25:15.1928964Z ##[debug]release.reason=ContinuousIntegration
2018-01-10T02:25:15.1929231Z ##[debug]agent.RootDirectory=C:\vstsagent\A1\_work
2018-01-10T02:25:15.1929487Z ##[debug]release.environmentName=Dev
2018-01-10T02:25:15.1929760Z ##[debug]agent.os=Windows_NT
2018-01-10T02:25:15.1930016Z ##[debug]agent.ToolsDirectory=C:\vstsagent\A1\_work\_tool
2018-01-10T02:25:15.1930392Z ##[debug]release.deployment.requestedForId=71559d41-1dc3-44a6-acbf-e0a58bc6bc47
2018-01-10T02:25:15.1930767Z ##[debug]release.artifacts.BOB-5-NET45.definitionName=BOB-5-NET45
2018-01-10T02:25:15.1931069Z ##[debug]release.deployment.requestedForEmail=tolga.balci@gmail.com
2018-01-10T02:25:15.1931336Z ##[debug]task.displayname=IIS Web App Deploy lead
2018-01-10T02:25:15.1931592Z ##[debug]release.artifacts.BOB-5-NET45.repository.provider=TfsGit
2018-01-10T02:25:15.1931871Z ##[debug]Parameters.ActionIISWebsite=CreateOrUpdateWebsite
2018-01-10T02:25:15.1932371Z ##[debug]build.definitionName=BOB-5-NET45
2018-01-10T02:25:15.1932622Z ##[debug]build.requestedForId=71559d41-1dc3-44a6-acbf-e0a58bc6bc47
2018-01-10T02:25:15.1933071Z ##[debug]system.teamProject=BOB
2018-01-10T02:25:15.1933429Z ##[debug]TIMCoreServicesWebsite=http://super.tim.thomsonlinear.com
2018-01-10T02:25:15.1933828Z ##[debug]requestedForId=71559d41-1dc3-44a6-acbf-e0a58bc6bc47
2018-01-10T02:25:15.1934106Z ##[debug]agent.jobstatus=Succeeded
2018-01-10T02:25:15.1934374Z ##[debug]system.defaultworkingdirectory=C:\vstsagent\A1\_work\r1\a
2018-01-10T02:25:15.1934732Z ##[debug]release.attemptNumber=1
2018-01-10T02:25:15.1935159Z ##[debug]release.triggeringartifact.alias=BOB-5-NET45
2018-01-10T02:25:15.1935415Z ##[debug]build.repository.id=2f786457-9c31-4683-9a03-92ff67c1dc03
2018-01-10T02:25:15.1935694Z ##[debug]system.teamFoundationCollectionUri=https://tolga.visualstudio.com/
2018-01-10T02:25:15.1935967Z ##[debug]release.skipartifactsDownload=False
2018-01-10T02:25:15.1936200Z ##[debug]Parameters.AppPoolName=
2018-01-10T02:25:15.1936439Z ##[debug]build.definitionId=17
2018-01-10T02:25:15.1936706Z ##[debug]release.artifacts.BOB-5-NET45.buildUri=vstfs:///Build/Build/148
2018-01-10T02:25:15.1936956Z ##[debug]build.type=Build
2018-01-10T02:25:15.1937343Z ##[debug]AZURE_HTTP_USER_AGENT=VSTS_c0473092-f876-42cb-bf30-1bc1ca912f5f_release_2_14_14_1
2018-01-10T02:25:15.1937764Z ##[debug]release.artifacts.BOB-5-NET45.sourceBranch=refs/heads/master
2018-01-10T02:25:15.1938015Z ##[debug]Parameters.AddBinding=True
2018-01-10T02:25:15.1938259Z ##[debug]agent.jobname=Release
2018-01-10T02:25:15.1938498Z ##[debug]system.timelineId=8455f688-16f3-46de-8bf5-0939f8e6ff90
2018-01-10T02:25:15.1938743Z ##[debug]agent.id=8
2018-01-10T02:25:15.1939113Z ##[debug]release.environmentId=14
2018-01-10T02:25:15.1939334Z ##[debug]system.teamProjectId=048c55e4-c19f-4503-bee7-da382fac2e92
2018-01-10T02:25:15.1939761Z ##[debug]agent.ServerOMDirectory=C:\vstsagent\A1\externals\vstsom
2018-01-10T02:25:15.1940006Z ##[debug]agent.workfolder=C:\vstsagent\A1\_work
2018-01-10T02:25:15.1940290Z ##[debug]build.sourceBranch=refs/heads/master
2018-01-10T02:25:15.1940558Z ##[debug]build.sourceVersion=c06b3a39149d0e961dde89800fa77f5441f712be
2018-01-10T02:25:15.1940825Z ##[debug]release.definitionEnvironmentId=2
2018-01-10T02:25:15.1941200Z ##[debug]release.deployment.startTime=2018-01-10 02:24:53Z
2018-01-10T02:25:15.1941599Z ##[debug]release.artifacts.BOB-5-NET45.sourceBranchName=master
2018-01-10T02:25:15.1941860Z ##[debug]build.projectId=048c55e4-c19f-4503-bee7-da382fac2e92
2018-01-10T02:25:15.1942247Z ##[debug]release.artifacts.BOB-5-NET45.projectName=BOB
2018-01-10T02:25:15.1942497Z ##[debug]release.artifacts.BOB-5-NET45.requestedForId=71559d41-1dc3-44a6-acbf-e0a58bc6bc47
2018-01-10T02:25:15.1942890Z ##[debug]build.repository.provider=TfsGit
2018-01-10T02:25:15.1943317Z ##[debug]system.hosttype=deployment
2018-01-10T02:25:15.1943669Z ##[debug]agent.name=TOLGALAPTOPDeploy
2018-01-10T02:25:15.1944028Z ##[debug]release.definitionName=BOB-NET4-DEPLOY
2018-01-10T02:25:15.1944261Z ##[debug]build.buildNumber=20180110.6
2018-01-10T02:25:15.1944500Z ##[debug]build.repository.name=BOB
2018-01-10T02:25:15.1944728Z ##[debug]release.releaseUri=vstfs:///ReleaseManagement/Release/14
2018-01-10T02:25:15.1945308Z ##[debug]system.collectionId=c0473092-f876-42cb-bf30-1bc1ca912f5f
2018-01-10T02:25:15.1945609Z ##[debug]Parameters.Bindings={"bindings":[{"protocol":"http","ipAddress":"All Unassigned","port":"80","hostname":"supertim.localhost","sslThumbprint":"","sniFlag":false}]}
2018-01-10T02:25:15.1945911Z ##[debug]release.releaseName=Release-11
2018-01-10T02:25:15.1946138Z ##[debug]release.releaseId=14
2018-01-10T02:25:15.1946355Z ##[debug]system.jobId=f9bd76f0-52d0-4fde-84b0-d9d932a7d561
2018-01-10T02:25:15.1946719Z ##[debug]system.planId=8455f688-16f3-46de-8bf5-0939f8e6ff90
2018-01-10T02:25:15.1946940Z ##[debug]release.requestedFor=Tolga Balci
2018-01-10T02:25:15.1947134Z ##[debug]System.Debug=true
2018-01-10T02:25:15.1947327Z ##[debug]build.buildUri=vstfs:///Build/Build/148
2018-01-10T02:25:15.1947515Z ##[debug]release.artifacts.BOB-5-NET45.type=Build
2018-01-10T02:25:15.1947896Z ##[debug]release.requestedForId=71559d41-1dc3-44a6-acbf-e0a58bc6bc47
2018-01-10T02:25:15.1948095Z ##[debug]build.buildId=148
2018-01-10T02:25:15.1948283Z ##[debug]release.deployPhaseId=13
2018-01-10T02:25:15.1948533Z ##[debug]release.releaseWebUrl=https://tolga.visualstudio.com/048c55e4-c19f-4503-bee7-da382fac2e92/_release?releaseId=14&_a=release-summary
2018-01-10T02:25:15.1948795Z ##[debug]agent.homedirectory=C:\vstsagent\A1
2018-01-10T02:25:15.1949017Z ##[debug]release.requestedForEmail=tolga.balci@gmail.com
2018-01-10T02:25:15.1949239Z ##[debug]release.artifacts.BOB-5-NET45.requestedFor=Tolga Balci
2018-01-10T02:25:15.1949512Z ##[debug]system.taskDefinitionsUri=https://tolga.visualstudio.com/
2018-01-10T02:25:15.1949728Z ##[debug]system.artifactsDirectory=C:\vstsagent\A1\_work\r1\a
2018-01-10T02:25:15.1949933Z ##[debug]agent.machinename=TOLGALAPTOP
2018-01-10T02:25:15.1950149Z ##[debug]build.requestedFor=Tolga Balci
2018-01-10T02:25:15.1950382Z ##[debug]system.enableAccessToken=False
2018-01-10T02:25:15.1961419Z ##[debug]Initiated variable substitution in config file : C:\vstsagent\A1\_work\r1\a\temp_web_package_8287370284012923\Content\T_C\build-agent\_work\2\s\TimWebservices.Lead\obj\any cpu\release\Package\PackageTmp\Web.Release.config
2018-01-10T02:25:15.1963871Z ##[debug]Detecting file encoding using BOM
2018-01-10T02:25:15.1996230Z ##[debug]Unable to find node with tag 'applicationSettings' in provided xml file.
2018-01-10T02:25:15.1996622Z ##[debug]Unable to find node with tag 'appSettings' in provided xml file.
2018-01-10T02:25:15.1997100Z ##[debug]Unable to find node with tag 'connectionStrings' in provided xml file.
2018-01-10T02:25:15.1997242Z ##[debug]Unable to find node with tag 'configSections' in provided xml file.
2018-01-10T02:25:15.1997453Z ##[debug]Skipped Updating file: C:\vstsagent\A1\_work\r1\a\temp_web_package_8287370284012923\Content\T_C\build-agent\_work\2\s\TimWebservices.Lead\obj\any cpu\release\Package\PackageTmp\Web.Release.config
2018-01-10T02:25:15.1999455Z ##[debug]Initiated variable substitution in config file : C:\vstsagent\A1\_work\r1\a\temp_web_package_8287370284012923\Content\T_C\build-agent\_work\2\s\TimWebservices.Lead\obj\any cpu\release\Package\PackageTmp\Web.config
2018-01-10T02:25:15.2002084Z ##[debug]Detecting file encoding using BOM
2018-01-10T02:25:15.2054648Z ##[debug]Processing substitution for xml node : applicationSettings
2018-01-10T02:25:15.2060747Z ##[debug]Processing substitution for xml node : appSettings
2018-01-10T02:25:15.2063819Z ##[debug]Processing substitution for xml node : connectionStrings
2018-01-10T02:25:15.2069036Z ##[debug]No substitution variables found for parameters.xml
2018-01-10T02:25:15.2071511Z ##[debug]Processing substitution for xml node : configSections
2018-01-10T02:25:15.2079657Z ##[debug]Skipped Updating file: C:\vstsagent\A1\_work\r1\a\temp_web_package_8287370284012923\Content\T_C\build-agent\_work\2\s\TimWebservices.Lead\obj\any cpu\release\Package\PackageTmp\Web.config
2018-01-10T02:25:15.2081899Z ##[debug]Initiated variable substitution in config file : C:\vstsagent\A1\_work\r1\a\temp_web_package_8287370284012923\Content\T_C\build-agent\_work\2\s\TimWebservices.Lead\obj\any cpu\release\Package\PackageTmp\bin\TimWebservices.CommonData.dll.config
2018-01-10T02:25:15.2082246Z ##[debug]Detecting file encoding using BOM
2018-01-10T02:25:15.2085420Z ##[debug]Unable to find node with tag 'applicationSettings' in provided xml file.
2018-01-10T02:25:15.2085744Z ##[debug]Unable to find node with tag 'appSettings' in provided xml file.
2018-01-10T02:25:15.2085920Z ##[debug]Unable to find node with tag 'connectionStrings' in provided xml file.
2018-01-10T02:25:15.2086074Z ##[debug]Unable to find node with tag 'configSections' in provided xml file.
2018-01-10T02:25:15.2086290Z ##[debug]Skipped Updating file: C:\vstsagent\A1\_work\r1\a\temp_web_package_8287370284012923\Content\T_C\build-agent\_work\2\s\TimWebservices.Lead\obj\any cpu\release\Package\PackageTmp\bin\TimWebservices.CommonData.dll.config
2018-01-10T02:25:15.2087468Z ##[debug]Initiated variable substitution in config file : C:\vstsagent\A1\_work\r1\a\temp_web_package_8287370284012923\Content\T_C\build-agent\_work\2\s\TimWebservices.Lead\obj\any cpu\release\Package\PackageTmp\bin\roslyn\VBCSCompiler.exe.config
2018-01-10T02:25:15.2089624Z ##[debug]Detecting file encoding using BOM
2018-01-10T02:25:15.2089823Z ##[debug]Unable to detect File encoding using BOM
2018-01-10T02:25:15.2091945Z ##[debug]Detecting file encoding without BOM
2018-01-10T02:25:15.2130766Z ##[debug]Unable to find node with tag 'applicationSettings' in provided xml file.
2018-01-10T02:25:15.2131056Z ##[debug]Processing substitution for xml node : appSettings
2018-01-10T02:25:15.2131244Z ##[debug]Unable to find node with tag 'connectionStrings' in provided xml file.
2018-01-10T02:25:15.2132097Z ##[debug]Unable to find node with tag 'configSections' in provided xml file.
2018-01-10T02:25:15.2132382Z ##[debug]Skipped Updating file: C:\vstsagent\A1\_work\r1\a\temp_web_package_8287370284012923\Content\T_C\build-agent\_work\2\s\TimWebservices.Lead\obj\any cpu\release\Package\PackageTmp\bin\roslyn\VBCSCompiler.exe.config
2018-01-10T02:25:15.2134100Z ##[debug]Initiated variable substitution in config file : C:\vstsagent\A1\_work\r1\a\temp_web_package_8287370284012923\Content\T_C\build-agent\_work\2\s\TimWebservices.Lead\obj\any cpu\release\Package\PackageTmp\bin\roslyn\csc.exe.config
2018-01-10T02:25:15.2135846Z ##[debug]Detecting file encoding using BOM
2018-01-10T02:25:15.2136034Z ##[debug]Unable to detect File encoding using BOM
2018-01-10T02:25:15.2136170Z ##[debug]Detecting file encoding without BOM
2018-01-10T02:25:15.2141421Z ##[debug]Unable to find node with tag 'applicationSettings' in provided xml file.
2018-01-10T02:25:15.2141672Z ##[debug]Unable to find node with tag 'appSettings' in provided xml file.
2018-01-10T02:25:15.2141819Z ##[debug]Unable to find node with tag 'connectionStrings' in provided xml file.
2018-01-10T02:25:15.2141984Z ##[debug]Unable to find node with tag 'configSections' in provided xml file.
2018-01-10T02:25:15.2142286Z ##[debug]Skipped Updating file: C:\vstsagent\A1\_work\r1\a\temp_web_package_8287370284012923\Content\T_C\build-agent\_work\2\s\TimWebservices.Lead\obj\any cpu\release\Package\PackageTmp\bin\roslyn\csc.exe.config
2018-01-10T02:25:15.2142792Z ##[debug]Initiated variable substitution in config file : C:\vstsagent\A1\_work\r1\a\temp_web_package_8287370284012923\Content\T_C\build-agent\_work\2\s\TimWebservices.Lead\obj\any cpu\release\Package\PackageTmp\bin\roslyn\csi.exe.config
2018-01-10T02:25:15.2144522Z ##[debug]Detecting file encoding using BOM
2018-01-10T02:25:15.2145933Z ##[debug]Unable to detect File encoding using BOM
2018-01-10T02:25:15.2146496Z ##[debug]Detecting file encoding without BOM
2018-01-10T02:25:15.2154495Z ##[debug]Unable to find node with tag 'applicationSettings' in provided xml file.
2018-01-10T02:25:15.2154796Z ##[debug]Unable to find node with tag 'appSettings' in provided xml file.
2018-01-10T02:25:15.2155115Z ##[debug]Unable to find node with tag 'connectionStrings' in provided xml file.
2018-01-10T02:25:15.2157675Z ##[debug]Unable to find node with tag 'configSections' in provided xml file.
2018-01-10T02:25:15.2158073Z ##[debug]Skipped Updating file: C:\vstsagent\A1\_work\r1\a\temp_web_package_8287370284012923\Content\T_C\build-agent\_work\2\s\TimWebservices.Lead\obj\any cpu\release\Package\PackageTmp\bin\roslyn\csi.exe.config
2018-01-10T02:25:15.2159592Z ##[debug]Initiated variable substitution in config file : C:\vstsagent\A1\_work\r1\a\temp_web_package_8287370284012923\Content\T_C\build-agent\_work\2\s\TimWebservices.Lead\obj\any cpu\release\Package\PackageTmp\bin\roslyn\vbc.exe.config
2018-01-10T02:25:15.2162072Z ##[debug]Detecting file encoding using BOM
2018-01-10T02:25:15.2162317Z ##[debug]Unable to detect File encoding using BOM
2018-01-10T02:25:15.2162459Z ##[debug]Detecting file encoding without BOM
2018-01-10T02:25:15.2170014Z ##[debug]Unable to find node with tag 'applicationSettings' in provided xml file.
2018-01-10T02:25:15.2170793Z ##[debug]Unable to find node with tag 'appSettings' in provided xml file.
2018-01-10T02:25:15.2171060Z ##[debug]Unable to find node with tag 'connectionStrings' in provided xml file.
2018-01-10T02:25:15.2171419Z ##[debug]Unable to find node with tag 'configSections' in provided xml file.
2018-01-10T02:25:15.2171834Z ##[debug]Skipped Updating file: C:\vstsagent\A1\_work\r1\a\temp_web_package_8287370284012923\Content\T_C\build-agent\_work\2\s\TimWebservices.Lead\obj\any cpu\release\Package\PackageTmp\bin\roslyn\vbc.exe.config
2018-01-10T02:25:15.2173740Z ##[debug]Initiated variable substitution in config file : C:\vstsagent\A1\_work\r1\a\temp_web_package_8287370284012923\Content\T_C\build-agent\_work\2\s\TimWebservices.Lead\obj\any cpu\release\Package\PackageTmp\packages.config
2018-01-10T02:25:15.2175680Z ##[debug]Detecting file encoding using BOM
2018-01-10T02:25:15.2179963Z ##[debug]Unable to find node with tag 'applicationSettings' in provided xml file.
2018-01-10T02:25:15.2180231Z ##[debug]Unable to find node with tag 'appSettings' in provided xml file.
2018-01-10T02:25:15.2180549Z ##[debug]Unable to find node with tag 'connectionStrings' in provided xml file.
2018-01-10T02:25:15.2180748Z ##[debug]Unable to find node with tag 'configSections' in provided xml file.
2018-01-10T02:25:15.2180987Z ##[debug]Skipped Updating file: C:\vstsagent\A1\_work\r1\a\temp_web_package_8287370284012923\Content\T_C\build-agent\_work\2\s\TimWebservices.Lead\obj\any cpu\release\Package\PackageTmp\packages.config
2018-01-10T02:25:15.2181141Z XML variable substitution applied successfully.
2018-01-10T02:25:15.2183786Z ##[debug]System.DefaultWorkingDirectory=C:\vstsagent\A1\_work\r1\a
2018-01-10T02:25:15.2188776Z ##[debug]Archiving C:\vstsagent\A1\_work\r1\a\temp_web_package_8287370284012923 to C:\vstsagent\A1\_work\r1\a\temp_web_package_04124051348310087.zip
2018-01-10T02:25:16.6303909Z ##[debug]Successfully created archive C:\vstsagent\A1\_work\r1\a\temp_web_package_04124051348310087.zip
2018-01-10T02:25:16.6304909Z ##[debug]rm -rf C:\vstsagent\A1\_work\r1\a\temp_web_package_8287370284012923
2018-01-10T02:25:16.6306161Z ##[debug]removing directory
2018-01-10T02:25:16.7167761Z ##[debug]SetParametersFile=C:\vstsagent\A1\_work\r1\a
2018-01-10T02:25:16.7169815Z ##[debug]Absolute path for pathSegments: C:\vstsagent\A1\_work\r1\a = C:\vstsagent\A1\_work\r1\a
2018-01-10T02:25:16.7170196Z ##[debug]build.sourcesDirectory=undefined
2018-01-10T02:25:16.7170435Z ##[debug]system.defaultWorkingDirectory=C:\vstsagent\A1\_work\r1\a
2018-01-10T02:25:16.7170651Z ##[debug]Absolute path for pathSegments: C:\vstsagent\A1\_work\r1\a = C:\vstsagent\A1\_work\r1\a
2018-01-10T02:25:16.7171027Z ##[debug]SetParametersFilepath supplied :false
2018-01-10T02:25:16.7623766Z ##[debug]Is the package an msdeploy package : true
2018-01-10T02:25:16.7627668Z ##[debug]Constructed msDeploy comamnd line arguments
2018-01-10T02:25:16.7631166Z ##[debug]appservice.msdeployretrycount=undefined
2018-01-10T02:25:16.7634824Z ##[debug]System.DefaultWorkingDirectory=C:\vstsagent\A1\_work\r1\a
2018-01-10T02:25:16.7640223Z ##[debug]the argument string is:
2018-01-10T02:25:16.7640667Z ##[debug] -verb:sync -source:package="'C:\vstsagent\A1\_work\r1\a\temp_web_package_04124051348310087.zip'" -dest:auto -setParam:name="'IIS Web Application Name'",value="'supertim.localhost/lead'" -enableRule:AppOffline
2018-01-10T02:25:16.7640900Z ##[debug]converting the argument string into an array of arguments
2018-01-10T02:25:16.7643005Z ##[debug]the array of arguments is:
2018-01-10T02:25:16.7643244Z ##[debug]arg#0: -verb:sync
2018-01-10T02:25:16.7643409Z ##[debug]arg#1: -source:package='C:\vstsagent\A1\_work\r1\a\temp_web_package_04124051348310087.zip'
2018-01-10T02:25:16.7643665Z ##[debug]arg#2: -dest:auto
2018-01-10T02:25:16.7643813Z ##[debug]arg#3: -setParam:name='IIS Web Application Name',value='supertim.localhost/lead'
2018-01-10T02:25:16.7643995Z ##[debug]arg#4: -enableRule:AppOffline
2018-01-10T02:25:16.7646219Z ##[debug]Absolute path for pathSegments: C:\Program Files\IIS\Microsoft Web Deploy V3\/msdeploy = C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy
2018-01-10T02:25:16.7648631Z ##[debug]check path : C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe
2018-01-10T02:25:16.7648944Z ##[debug]msdeploy=C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe
2018-01-10T02:25:16.7650992Z ##[debug]C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe arg: ["-verb:sync","-source:package='C:\\vstsagent\\A1\\_work\\r1\\a\\temp_web_package_04124051348310087.zip'","-dest:auto","-setParam:name='IIS Web Application Name',value='supertim.localhost/lead'","-enableRule:AppOffline"]
2018-01-10T02:25:16.7651595Z ##[debug]C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe arg: ["-verb:sync","-source:package='C:\\vstsagent\\A1\\_work\\r1\\a\\temp_web_package_04124051348310087.zip'","-dest:auto","-setParam:name='IIS Web Application Name',value='supertim.localhost/lead'","-enableRule:AppOffline"]
2018-01-10T02:25:16.7654576Z ##[debug]exec tool: C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe
2018-01-10T02:25:16.7654901Z ##[debug]exec tool: C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe
2018-01-10T02:25:16.7655180Z ##[debug]Arguments:
2018-01-10T02:25:16.7655396Z ##[debug]Arguments:
2018-01-10T02:25:16.7655595Z ##[debug]   -verb:sync
2018-01-10T02:25:16.7655868Z ##[debug]   -verb:sync
2018-01-10T02:25:16.7656022Z ##[debug]   -source:package='C:\vstsagent\A1\_work\r1\a\temp_web_package_04124051348310087.zip'
2018-01-10T02:25:16.7656221Z ##[debug]   -source:package='C:\vstsagent\A1\_work\r1\a\temp_web_package_04124051348310087.zip'
2018-01-10T02:25:16.7656369Z ##[debug]   -dest:auto
2018-01-10T02:25:16.7656665Z ##[debug]   -dest:auto
2018-01-10T02:25:16.7656790Z ##[debug]   -setParam:name='IIS Web Application Name',value='supertim.localhost/lead'
2018-01-10T02:25:16.7656949Z ##[debug]   -setParam:name='IIS Web Application Name',value='supertim.localhost/lead'
2018-01-10T02:25:16.7657086Z ##[debug]   -enableRule:AppOffline
2018-01-10T02:25:16.7657228Z ##[debug]   -enableRule:AppOffline
2018-01-10T02:25:16.7674163Z [command]"C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe" -verb:sync -source:package='C:\vstsagent\A1\_work\r1\a\temp_web_package_04124051348310087.zip' -dest:auto -setParam:name='IIS Web Application Name',value='supertim.localhost/lead' -enableRule:AppOffline
2018-01-10T02:25:17.2444463Z ##[debug]rc:4294967295
2018-01-10T02:25:17.2444964Z ##[debug]rc:4294967295
2018-01-10T02:25:17.2445339Z ##[debug]success:false
2018-01-10T02:25:17.2445515Z ##[debug]success:false
2018-01-10T02:25:17.2470592Z ##[debug]System.DefaultWorkingDirectory=C:\vstsagent\A1\_work\r1\a
2018-01-10T02:25:17.2504907Z ##[error]Failed to deploy web package to IIS website.
2018-01-10T02:25:17.2505277Z ##[debug]Processed: ##vso[task.issue type=error;]Failed to deploy web package to IIS website.
2018-01-10T02:25:17.2505425Z ##[debug]{}
2018-01-10T02:25:17.2505653Z ##[debug]System.DefaultWorkingDirectory=C:\vstsagent\A1\_work\r1\a
2018-01-10T02:25:17.2507735Z ##[error]Error: Could not find a part of the path 'C:\inetpub\wwwroot\lead\App_Offline.htm'.
Error count: 1.

2018-01-10T02:25:17.2507883Z ##[debug]Processed: ##vso[task.issue type=error;]Error: Could not find a part of the path 'C:\inetpub\wwwroot\lead\App_Offline.htm'.%0D%0AError count: 1.%0D%0A
2018-01-10T02:25:17.2508110Z ##[debug]rm -rf C:\vstsagent\A1\_work\r1\a\error.txt
2018-01-10T02:25:17.2508366Z ##[debug]removing file
2018-01-10T02:25:17.2513094Z ##[debug]task result: Failed
2018-01-10T02:25:17.2513503Z ##[error]Error: C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe failed with return code: 4294967295
2018-01-10T02:25:17.2513702Z ##[debug]Processed: ##vso[task.issue type=error;]Error: C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe failed with return code: 4294967295
2018-01-10T02:25:17.2534427Z ##[debug]Processed: ##vso[task.complete result=Failed;]Error: C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe failed with return code: 4294967295
2018-01-10T02:25:17.2706499Z ##[section]Finishing: IIS Web App Deploy lead`

**Comment by jtermine** [comment]
I also ran into this problem today with Azure DevOps, similar to what @tolgabalci described.
