### ISSUE TITLE
ServiceFabricDeployTask throws Xml  parsing error when EnvironmentOverride is added to the ApplicationManifest

### ISSUE THREAD

**Issue by kbulte** [Microsoft/vsts-tasks#3521]
I ran into  the following issue when I specify EnvironmentOverrides in the ApplicationManifest.xml

**##[error]Exception while parsing XML file: C:\Users\buildguest\AppData\Local\Temp\TestApplicationPackage_2712596271\mu5idquj.uwq\applicationpackage\ApplicationManifest.xml**

The overrides are specified as described in the following [documentation ](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-manage-multiple-environment-app-configuration)

    <ServiceManifestImport>
        <ServiceManifestRef ServiceManifestName="WebApi1Pkg" ServiceManifestVersion="1.0.0" />
        <ConfigOverrides />
        <EnvironmentOverrides CodePackageRef="Code">
          <EnvironmentVariable Name="MyEnvVariable" Value="mydata"/>
        </EnvironmentOverrides>
    </ServiceManifestImport>
    <DefaultServices>
        <Service Name="WebApi1">
          <StatelessService ServiceTypeName="WebApi1Type" InstanceCount="[WebApi1_InstanceCount]">
            <SingletonPartition />
          </StatelessService>
        </Service>
    </DefaultServices>

When I remove the EnvironmentOverride the application is deployed to the cluster.

I checked the xml for well-formedness and I can do a successful manual publish of the application from within Visual Studio 2015.

Is there a way to get the line number and position where exactly the task is failing on?

**Comment by mikanyg** [comment]
Have you tried adding a release variable name System.Debug and set it to true? It will output detailed logs from the VSTS tasks.

**Comment by kbulte** [comment]
@mikanyg I added the Debug variable and it outputs an error on schema validation

>FileName: C:\Users\buildguest\AppData\Local\Temp\TestApplicationPackage_2601601442\i0id2ksp.hj1\applicationpackage\ApplicationManifest.xml ---> System.InvalidOperationException: There is an error in XML document (12, 6). ---> System.Xml.Schema.XmlSchemaValidationException: The element 'ServiceManifestImport' in namespace 'http://schemas.microsoft.com/2011/01/fabric' has invalid child element 'EnvironmentOverrides' in namespace 'http://schemas.microsoft.com/2011/01/fabric'. List of possible elements expected: 'ConfigOverrides, Policies' in namespace 'http://schemas.microsoft.com/2011/01/fabric'.

So I added an inline powershell script which prints out the registry key value of"HKLM:\SOFTWARE\Microsoft\Service Fabric SDK". It seems VSTS is not using the latest Service Fabric SDK:

> @{FabricSDKVersion=2.3.311.9590; PSPath=Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Service Fabric SDK; PSParentPath=Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft; PSChildName=Service Fabric SDK; PSDrive=HKLM; PSProvider=Microsoft.PowerShell.Core\Registry}

'EnvironmentOverrides' was introduced in the latest Service Fabric SDK 2.4.145.9494 based on this thread [here](https://github.com/Azure/service-fabric-issues/issues/88)

Someone has an idea when the SDK version will be upgraded to SDK 2.4.145.9494?

**Comment by mikanyg** [comment]
I am not sure, but I think they update the Hosted Agent images every 2-3 months, you can probably skim through the VSTS release notes, where they mention when the Hosted Agent image has been updated.

**Comment by kbulte** [comment]
Meanwhile the Service Fabric team released SDK version 2.4.164. When can we expect this version to be installed on the VSTS hosted agent?

**Comment by MikkelHegn** [comment]
@chrisrpatterson Can you help with an update?

**Comment by jasonchester** [comment]
Also having this issue. Attaching log file with System.Debug = true

[3_Deploy Service Fabric Application.txt](https://github.com/Microsoft/vsts-tasks/files/772690/3_Deploy.Service.Fabric.Application.txt)

**Comment by rh78** [comment]
Unfortunately 2.4.164 fails during installation. It says a newer version is already installed!!

**Comment by MikkelHegn** [comment]
@rh78: Where are you trying to install the SDK?

**Comment by rh78** [comment]
In the meanwhile I got it to install (downloading the MSI directly) (Windows 10). But then still there was a crash when opening the project in Visual Studio. But i solved it: it was because Visual Studio was set to German. When set to english everything works.

**Comment by dbreshears** [comment]
@rh78. We have a known issue when installing Localized versions of the tooling on the 5.4.164 release.   We are working on a fix for this now.

**Comment by LaevaertK** [comment]
@kbulte @MikkelHegn Also having this problem (VSTS Hosted Agent doesn't have SDK version 2.4.164 installed)...
Any update?

**Comment by dbreshears** [comment]
@rh78.    Can you try the localized tooling again. This should be fixed.

**Comment by rh78** [comment]
OK now I also run into the VSTS Hosted Agent issue as we're working on release. Please fix that.

**Comment by rh78** [comment]
I fixed it in the meanwhile by creating a separate ServiceManifest.xml/ApplicationManifest, without environmentoverride, and handled passing parameter through command line arguments. Then upon VSTS build I replace the files, effectively working around the problem

**Comment by MikkelHegn** [comment]
Thanks @rh78 - we are working on getting the SDK updated on the hosted build agents. As soon as I have an eta, we'll let you know.

**Comment by MikkelHegn** [comment]
Hi all, we expect to have the hosted build agents updated in the next 7-10 days. If you need a workaround, then currently the best is to ring you own agent in the meantime.

**Comment by kbulte** [comment]
@MikkelHegn I saw the  hosted build agent uses the latest SF SDK today:

![image](https://cloud.githubusercontent.com/assets/1887008/23740735/3d7fd17a-04a5-11e7-9d30-29787d69db66.png)

Thank you for your help.

**Comment by ham-steamer** [comment]
This is still an issue. Here is the relevant portion of my ApplicationManifest.xml:
`<ServiceManifestImport>
    <ServiceManifestRef ServiceManifestName="HangFirePkg" ServiceManifestVersion="1.0.0" />
    <ConfigOverrides />
    <EnvironmentOverrides CodePackageRef="Code">
      <EnvironmentVariable Name="DeploymentEnvironment" Value="[DeploymentEnvironment]"/>
    </EnvironmentOverrides>
  </ServiceManifestImport>`

And the output from the Deploy Service Application task:
`2018-09-05T16:27:44.3230344Z Service fabric SDK version: 2.4.164.9494.
2018-09-05T16:27:52.1077847Z ##[error]Exception while parsing XML file: C:\Users\buildguest\AppData\Local\Temp\TestApplicationPackage_6237072557\e4d4bon3.jlu\Release\ApplicationManifest.xml`

**Comment by wouterroos** [comment]
Hi,

Responsing to this thread since I got a similar issue when attempting to deploy a service that uses the new ManagedIdentities tag in the ServiceManifest.xml:

`System.InvalidOperationException: There is an error in XML document (18, 6). ---> System.Xml.Schema.XmlSchemaValidationException: The element 'Resources' in namespace 'http://schemas.microsoft.com/2011/01/fabric' has invalid child element 'ManagedIdentities' in namespace 'http://schemas.microsoft.com/2011/01/fabric'. List of possible elements expected: 'Endpoints' in namespace 'http://schemas.microsoft.com/2011/01/fabric'.`

Agent is running SDK version 3.3.617.9590 while my local machine 3.4.664
