### ISSUE TITLE
App Service Deploy fails with ERROR_CONNECTION_TERMINATED

### ISSUE THREAD

**Issue by shyamsrini** [Microsoft/vsts-tasks#4171]
The Azure App Service Deploy task keeps on failing with the below error. On Multiple retries , same error is observed with "**position**" changing in every error message

[error]Failed to deploy App Service.
[error]Error Code: ERROR_CONNECTION_TERMINATED
More Information: Web Deploy experienced a connection problem with the server and had to terminate the connection.  Contact your server administrator if the problem persists.  Learn more at: http://go.microsoft.com/fwlink/?LinkId=221672#ERROR_CONNECTION_TERMINATED.
Error: Unexpected end of file has occurred. The following elements are not closed: results. Line 1, **position** 4886.
Error count: 1.

**Comment by vincentdass** [comment]
@shyamsrini , Can you please share the current task version ?
We have fixed this issue in 3.3.0 version.

**Comment by shyamsrini** [comment]
@vincentdass  The issue was seen in 3.2.1 version. However, when creating the task .. I can only choose only version 3.* from the drop-down menu. Will the task always run with in 3.3.0 from now on?

**Comment by vincentdass** [comment]
@shyamsrini , The deployment is in progress and the fix will be available in a week or two.
Can you please try the following steps to mitigate the issue:
* Enable Always on Option in your Application settings from Azure Portal.
![image](https://cloud.githubusercontent.com/assets/20121508/25516673/890f6e62-2c09-11e7-9030-32d58a88747a.png)

* Try hitting https://< AppServiceName >.azurewebsites.net from your browser.
* Try hitting https://< AppServiceName >.scm.azurewebsites.net from your browser.

Is this issue happening consistently?
Have you deployed to this app previously without any issue or is this the first deployment for the app ?

**Comment by arjgupta** [comment]
Hi @shyamsrini , is the issue still happening for you? Can you please share the full debug logs with RM_Customer_Queries@microsoft.com . You can generate the debug logs by setting the system.debug variable to true in the variables tab

**Comment by shyamsrini** [comment]
@arjgupta @vincentdass 
Hi, the issue is not happening anymore , after moving to latest version. I havent seen the issue for past 405 days.  Thanks a lot for your prompt response and your help .

**Comment by ggirard07** [comment]
I am currently hitting this issue with version `3.3.28`
```
2017-12-07T21:06:00.6139340Z ##[warning]Error Code: ERROR_CONNECTION_TERMINATED
More Information: Web Deploy experienced a connection problem with the server and had to terminate the connection.  Contact your server administrator if the problem persists.  Learn more at: http://go.microsoft.com/fwlink/?LinkId=221672#ERROR_CONNECTION_TERMINATED.
Error: Unexpected end of file has occurred. The following elements are not closed: results. Line 1, position 370.
Error count: 1.
```

**Comment by vincentdass** [comment]
@ggirard07 , Can you please share the whole release log?
We retry the deployment again for ERROR_CONNECTION_TERMINATED and it should have fixed the issue.

**Comment by ggirard07** [comment]
I just got one, how can i share the logs? I just don't have the system.debug enabled on that release...

**Comment by vincentdass** [comment]
@ggirard07 , share the current release log here. (copy-paste is also preferable).

**Comment by pkumar1986** [comment]
I have the same issue while publish a web application to azure -
1. Error from VS 2015 : Web deployment task failed. (Web Deploy experienced a connection problem with the server and had to terminate the connection.  Contact your server administrator if the problem persists.  Learn more at: http://go.microsoft.com/fwlink/?LinkId=221672#ERROR_CONNECTION_TERMINATED.

2. And also Error while using "git push azureprod master" from CMD.
fatal: unable to access 'https://ps-helloworld@-------.git/': Failed to connect to fi
rstazureapp.scm.azurewebsites.net port 443: Timed out

I am using B1 app service plan in azure web app.
Is it a connection issue or am I missing anthing ?

Tips to resolve this issue is much appreciated.

**Comment by pkumar1986** [comment]
I have the same issue while publish a web application to azure -
1. Error from VS 2015 : Web deployment task failed. (Web Deploy experienced a connection problem with the server and had to terminate the connection.  Contact your server administrator if the problem persists.  Learn more at: http://go.microsoft.com/fwlink/?LinkId=221672#ERROR_CONNECTION_TERMINATED.

2. And also Error while using "git push azureprod master" from CMD.
fatal: unable to access 'https://ps-helloworld@-------.git/': Failed to connect to fi
rstazureapp.scm.azurewebsites.net port 443: Timed out

I am using B1 app service plan in azure web app.
Is it a connection issue or am I missing anthing ?

Tips to resolve this issue is much appreciated.

**Comment by magnuskarlssonhm** [comment]
I'm unexpectedly hitting the same error. Seems very weird to me. I've been using this feature for several years and this is first time I hit this. Canät figure out why. How to debug?

**Comment by Ajay-MS** [comment]
@magnuskarlssonhm 

- Are you using task version of Azure App service task? 
- With version 4.* of the task, Tryout zip deploys option instead of web app deploys. 
- If still, you face the issue, share debug logs.  Debug logs can be enabled by adding a release definition variable `system.debug` with value `true`.

**Comment by VAMsumannenavath** [comment]
i am trying to deploy to function app using ci/cd pipeline and i am getting this error
2020-02-07T08:32:03.1876574Z ##[error]Failed to deploy web package to App Service.
2020-02-07T08:32:03.1885343Z ##[error]Error Code: ERROR_CONNECTION_TERMINATED
More Information: Web Deploy experienced a connection problem with the server and had to terminate the connection.  Contact your server administrator if the problem persists.  Learn more at: http://go.microsoft.com/fwlink/?LinkId=221672#ERROR_CONNECTION_TERMINATED.
Error: Unexpected end of file has occurred. The following elements are not closed: results. Line 1, position 550.
Error count: 1.

**Comment by magnuskarlssonhm** [comment]
Hi,

Who are you and what are you deploying to github? Is this related to Afound?

Regards/Hälsningar
MAGNUS KARLSSON
BUSINESS TECHNOLOGY STRATEGIST
AFOUND / HM GROUP
PHONE: +46 73 074 1403
This email is nonbinding unless and until a more formal and definitive written contract between the parties is signed.

**Comment by sergiosolorzano** [comment]
I had fiddler capturing and that caused it. Close / stop capturing and that solved it.

**Comment by refex** [comment]
> I had fiddler capturing and that caused it. Close / stop capturing and that solved it.

Closing Fiddler solved the same problem for me, thank you!
