### ISSUE TITLE
Service Fabric Cluster Deploy - 64K Environment Variable Limit

### ISSUE THREAD

**Issue by FBNitro** [Microsoft/vsts-tasks#5078]
According to the VSTS Task Lib, there was a defect with Environment Variables stopping if you had > 64K of Environment variables.  VSTS Task Lib has claimed that this was fixed, and that tasks need to update to the latest version.  I recently hit this scenario with the Service Fabric Cluster Deploy.

Please release an updated version with this fix, this defect is blocking production release of our software.

VSTS Task Lib link;
https://github.com/Microsoft/vsts-task-lib/issues/228

My logs:
`2017-08-22T00:32:02.6122794Z ##[section]Starting: Deploy Application to Cluster
2017-08-22T00:32:02.6122794Z ==============================================================================
2017-08-22T00:32:02.6122794Z Task         : Service Fabric Application Deployment
2017-08-22T00:32:02.6122794Z Description  : Deploy a Service Fabric application to a cluster.
2017-08-22T00:32:02.6132803Z Version      : 1.3.10
2017-08-22T00:32:02.6132803Z Author       : Microsoft Corporation
2017-08-22T00:32:02.6132803Z Help         : [More Information](https://go.microsoft.com/fwlink/?LinkId=820528)
2017-08-22T00:32:02.6132803Z ==============================================================================
2017-08-22T00:32:03.6725203Z Add-Type : The environment block used to start a process cannot be longer than 65535 bytes.  Your environment block is 
2017-08-22T00:32:03.6725203Z 67130 bytes long.  Remove some environment variables and try again.
2017-08-22T00:32:03.6725203Z At D:\a\_tasks\ServiceFabricDeploy_<GUID>\1.3.10\ps_modules\VstsTaskSdk\LongPathFunctions
2017-08-22T00:32:03.6725203Z .ps1:212 char:1
2017-08-22T00:32:03.6725203Z + Add-Type -Debug:$******** -TypeDefinition @'
2017-08-22T00:32:03.6725203Z + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2017-08-22T00:32:03.6735207Z     + CategoryInfo          : NotSpecified: (:) [Add-Type], InvalidOperationException
2017-08-22T00:32:03.6735207Z     + FullyQualifiedErrorId : System.InvalidOperationException,Microsoft.PowerShell.Commands.AddTypeCommand
2017-08-22T00:32:03.6735207Z  
2017-08-22T00:32:03.7145188Z Add-Type : The environment block used to start a process cannot be longer than 65535 bytes.  Your environment block is 
2017-08-22T00:32:03.7155197Z 67130 bytes long.  Remove some environment variables and try again.
2017-08-22T00:32:03.7155197Z At 
2017-08-22T00:32:03.7155197Z D:\a\_tasks\ServiceFabricDeploy_<GUID>\1.3.10\ps_modules\VstsTaskSdk\VstsTaskSdk.psm1:74 
2017-08-22T00:32:03.7155197Z char:1
2017-08-22T00:32:03.7155197Z + Add-Type -WarningAction SilentlyContinue -Debug:$******** -TypeDefinitio ...
2017-08-22T00:32:03.7155197Z + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2017-08-22T00:32:03.7155197Z     + CategoryInfo          : NotSpecified: (:) [Add-Type], InvalidOperationException
2017-08-22T00:32:03.7155197Z     + FullyQualifiedErrorId : System.InvalidOperationException,Microsoft.PowerShell.Commands.AddTypeCommand`

**Comment by tlisiecki** [comment]
Hi,
I have just run into the same problem with that task. Really hoped to never see that error again...
This is happening on the latest, available for me, agent version:
Agent.Version: 2.120.2

**Comment by bishal-pdMSFT** [comment]
We are planning this work next week and should be hot-fixed by EOD next week(09/08)

**Comment by FBNitro** [comment]
Thanks for the status update.

**Comment by tlisiecki** [comment]
Hi @bishal-pdMSFT 
Any news on that hotfix?

**Comment by bishal-pdMSFT** [comment]
@tlisiecki we are working on this. This got pushed out a bit due to some other high priority items.

**Comment by tlisiecki** [comment]
Hi @bishal-pdMSFT. I see changes are now in master and a new version of VSTS Agent was released ('2.123.0'). I tried to run the release but the VSTS Service Fabric Application Deployment Task was still in version 1.3.10 and it still fails. Any idea when the new versions of tasks will be rolled out?

**Comment by bishal-pdMSFT** [comment]
this is deployed now.

**Comment by tlisiecki** [comment]
Thank you @bishal-pdMSFT , much appreciated. I`ll check how it looks like on my account.

**Comment by bishal-pdMSFT** [comment]
@tlisiecki I am closing this issue. please re-open if you still the problem.

**Comment by tlisiecki** [comment]
Hi @bishal-pdMSFT 
Yeah, please do. All the SF Tasks work fine now.
The only task I still see the errors in is Visual Studio Test Agent Deployment (v.2.1.25) but the error  doesn`t seem to cause any issues.

**Comment by FBNitro** [comment]
Closing, I have confirmed that is is resolved also (original reporter).
