### ISSUE TITLE
Run functional tests - Side by side VS15 and VS17 Test agent installations cause intermittent failures

### ISSUE THREAD

**Issue by xenalite** [Microsoft/vsts-tasks#5135]
I have 2 release definitions that fail to run tests intermittently.
Here is the log from the task:
[25_Run system tests on target.txt](https://github.com/Microsoft/vsts-tasks/files/1257202/25_Run.system.tests.on.target.txt)

Here is the log from Test Agent host:
[DTAExecutionHost.exe.txt](https://github.com/Microsoft/vsts-tasks/files/1257215/DTAExecutionHost.exe.txt)

Here is test agent deployment task configuration:
![image](https://user-images.githubusercontent.com/4509839/29779275-f5c51218-8c09-11e7-823e-f205b379d259.png)

We use VS17 TA to run the tests, but the test VM still has a VS15 Update 3 TA installed on it.
We have other release definitions, which were running tests on VS15 Update 3 TA with VS17 TA installed on the same VM. They were also failing until we uninstalled VS17 TA. We do not run tests in parallel on same machines.

**Comment by nigurr** [comment]
@xenalite Can you please share the below information?

Are you using TFS On-Prem or VSTS? 
This was addressed in TFS 2017 Update 2.

**Comment by xenalite** [comment]
We are on VSTS.

**Comment by nigurr** [comment]
@xenalite Can you please enable "Update Test agent" verify once. We do recommend **not** to install 2015 and 2017 test agents side by side.

**Comment by xenalite** [comment]
@nigurr I enabled "Update Test Agent" option in the deploy task. I ran a few more test runs afterwards. One of them just failed with the same error. 
I will uninstall VS15u3 agent from test VM as per recommendation and see if I can still reproduce this issue.

**Comment by xenalite** [comment]
@nigurr 
I uninstalled VS15u3 and VS17 TAs and let the task deploy the most recent version.
Afterwards, I am still able to reproduce the same issue with only VS17 TA installed.

**Comment by nigurr** [comment]
@xenalite can you please enable "Run UI Tests" and check if it fixes your issue. We are suspecting that "test user account" doesn't have active session on the remote machine.

**Comment by xenalite** [comment]
@nigurr We run tests with a service account that has explicitly denied logon rights. This is not an option for us and in fact fails with this:

> Stopping test machine setup as it exceeded maximum number of reboots. If you are running test agent in interactive mode, please make sure that autologon is enabled and no legal notice is displayed on logon in test machines. ---> System.Management.Automation.RuntimeException: Stopping test machine setup as it exceeded maximum number of reboots. If you are running test agent in interactive mode, please make sure that autologon is enabled and no legal notice is displayed on logon in test machines. ---> System.Management.Automation.RuntimeException: Stopping test machine setup as it exceeded maximum number of reboots. If you are running test agent in interactive mode, please make sure that autologon is enabled and no legal notice is displayed on logon in test machines.

**Comment by nigurr** [comment]
@xenalite Thanks for letting know. This issue is being tracked here: https://github.com/Microsoft/vsts-tasks/issues/5213

For Non-UI tests, we advice you to use "Test Agent 2015" or alternatively, can you please login to the test machine with test user account and disconnect from the computer. this will make sure the user is logged in and it will unblock your scenario.

**Comment by xenalite** [comment]
@nigurr 
We are still seeing this issue, albeit less often, with TA 2015 U3.

> 2017-09-14T14:32:04.3283292Z ##[warning]DistributedTests: Test run is aborted. Logging details of the run logs.
> 2017-09-14T14:32:04.4066816Z ##[warning]DistributedTests: New test run created.
> 2017-09-14T14:32:04.4066816Z Test Run queued for Project Collection Build Service (<VSTSInstance>).
> 2017-09-14T14:32:04.4066816Z 
> 2017-09-14T14:32:04.4066816Z ##[warning]DistributedTests: Test discovery started.
> 2017-09-14T14:32:04.4066816Z ##[warning]DistributedTests: UnExpected error occurred during test execution. Try again.
> 2017-09-14T14:32:04.4066816Z ##[warning]DistributedTests: Error : Some tests could not run because all test agents of this testrun were unreachable for long time. Ensure that all testagents are able to communicate with the server and retry again.
> 2017-09-14T14:32:04.4066816Z 
> 2017-09-14T14:32:04.4066816Z ##[warning]DistributedTests: Test run aborted. Test run id: 45775
> 2017-09-14T14:32:04.4066816Z ##[error]System.Exception: The test run was aborted, failing the task.
> 2017-09-14T14:32:04.5002201Z ##[error]PowerShell script completed with 1 errors.
> 2017-09-14T14:32:04.5002201Z ##[section]Finishing: Run tests on target

[DTAExecutionHost.exe.txt](https://github.com/Microsoft/vsts-tasks/files/1303446/DTAExecutionHost.exe.txt)

Can you please advise what is the recommended way of running non UI tests on a remote test VM?
Should we keep using "Run functional tests" task or should we create a Deployment Group and run "Visual Studio Tests" task on that group?

**Comment by nigurr** [comment]
@xenalite 
We recommend you to move to VsTest v2 task and use Build agent in Interactive mode [v2.120.x supports this functionality - https://github.com/Microsoft/vsts-agent/releases/tag/v2.120.2]. We will be publishing the blog about same sooner.

**Comment by bergmeister** [comment]
@nigurr Please re-open as this is being blocked by #4993 . I see you have deprecated the task but you do not seem to offer an alternative for remote test execution that requires interaction for scenarios such as UI tests.
