### ISSUE TITLE
Task: Download Build Artifacts - No longer respecting proxy settings.

### ISSUE THREAD

**Issue by rosstified** [Microsoft/vsts-tasks#6045]
## Environment
VSTS (cpaaustralia.visualstudio.com)

- Agent - Private: 
  From the output:
    - 	[AGENT_VERSION] --> [2.124.0]
    -  [AGENT_OS] --> [Windows_NT]

## Issue Description
The Download build artifacts does not respect the proxy settings of the agent. It was until yesterday. Appears there have been some changes made recently to the task which may have caused the issue? Unsure.

Confirmed on the machine that other tasks are going via Proxy as expected, this task is not.

### Error logs
2017-12-14T23:01:50.4842396Z ##[section]Starting: Download artifact - build
2017-12-14T23:01:50.5022406Z ==============================================================================
2017-12-14T23:01:50.5022406Z Task         : Download Build Artifacts
2017-12-14T23:01:50.5022406Z Description  : Download Build Artifacts
2017-12-14T23:01:50.5022406Z Version      : 0.127.3
2017-12-14T23:01:50.5022406Z Author       : Microsoft Corporation
2017-12-14T23:01:50.5022406Z Help         : 
2017-12-14T23:01:50.5032406Z ==============================================================================
2017-12-14T23:01:52.1433411Z Error : in getBuild, so retrying => retries pending  : 4
2017-12-14T23:01:56.1455709Z Error : in getBuild, so retrying => retries pending  : 3
2017-12-14T23:02:00.1457917Z Error : in getBuild, so retrying => retries pending  : 2
2017-12-14T23:02:04.1460196Z Error : in getBuild, so retrying => retries pending  : 1
2017-12-14T23:02:08.1512512Z ##[error]Failed in getBuild with error: Error: connect ECONNREFUSED 13.75.145.145:443
2017-12-14T23:02:08.2822602Z ##[error]Error: connect ECONNREFUSED 13.75.145.145:443
2017-12-14T23:02:08.2892582Z ##[section]Async Command Start: Telemetry
2017-12-14T23:02:08.3052602Z ##[section]Async Command End: Telemetry
2017-12-14T23:02:08.3062594Z ##[section]Finishing: Download artifact - build

**Comment by rosstified** [comment]
As a work around - we've verified adding the HTTP_PROXY and HTTPS_PROXY as environment variables as a work around has allowed us to continue to work, but we've needed to make this to all build and deployment agents.

**Comment by omeshp** [comment]
Thanks for reporting the issue  @rosstified, I will have a look at it today.

**Comment by omeshp** [comment]
@rosstified We have fixed the task to work with proxy, can you confirm that you are not facing this issue anymore?

**Comment by rosstified** [comment]
Thanks @omeshp let me get out team to try it on one of the servers and try again. Any specific we need to do or will task always download? (i.e. need to restart the agent or anything?)

**Comment by rosstified** [comment]
@omeshp confirmed with the team today that this resolved the need for the proxy setting, and we're back in action. Thanks for the quick resolution

**Comment by omeshp** [comment]
@rosstified Thanks! for confirmation.

**Comment by jimmywyatt** [comment]
@rosstified i'm having the same issue, did your team have to do anything to get it to update?

**Comment by omeshp** [comment]
@jimmywyatt We fixed the above issue and no update is required from your side. 

You might be facing another issue with using proxy, where passwords containing \ are not working? https://github.com/Microsoft/vsts-rm-extensions/issues/341

Can you confirm if that is the case?

**Comment by jimmywyatt** [comment]
@omeshp I don't want to pollute this thread so I might be better off creating a new issue then. In our case we don't specify the username/password as part of the proxy file. Everything else seems to work, just the download artifact task that fails.

**Comment by omeshp** [comment]
@jimmywyatt what is you vsts-account name?

**Comment by jimmywyatt** [comment]
@omeshp  ipes.visualstudio.com

**Comment by omeshp** [comment]
Ok, I have disabled the feature for your account, It should be working as expected now. I will look at why you are seeing issue with proxy when the feature is enabled.

**Comment by christopheph** [comment]
@omeshp We have the same issue at my client. our account is candriamtfs.visualstudio.com
could you make the same for us ?

**Comment by omeshp** [comment]
@christopheph Ok, I have disabled it on your account too and all other accounts showing these failures from our telemetry.

**Comment by christopheph** [comment]
@omeshp it works, but i needed to create a new release in order to make it working because existing releases were still failing. Thanks

**Comment by bigmck1** [comment]
@omeshp I am getting the issue on https://tgpsystemdevelopment.visualstudio.com how do I go about resolving it?

**Comment by omeshp** [comment]
@bigmck1 Can you mail me release logs at omeshp@microsoft.com. I have disabled the feature flag for your account for now. Also I have logged an issue at https://github.com/Microsoft/typed-rest-client/issues/49 to get this fixed.

**Comment by bigmck1** [comment]
Many thanks, Ive emailed from my company account

**Comment by omeshp** [comment]
Hi @jimmywyatt, I am trying to figure out why Download Build Artifacts task isn't working with your proxy configuration. Can you confirm if your proxy server is using NTLM for authentication?

**Comment by jimmywyatt** [comment]
@omeshp i can confirm it is

**Comment by omeshp** [comment]
@jimmywyatt Thanks!

**Comment by allanmoller** [comment]
Having exact same problem out of a sudden, seems to be many fixes, can someone point me in right direction?

**Comment by omeshp** [comment]
@allanmoller Are you still facing this issue?
