### ISSUE TITLE
TLS 1.2 Error on Azure SQL DB Task

### ISSUE THREAD

**Issue by simplesi** [Microsoft/vsts-tasks#6925]
## Environment
- Server - VSTS or TFS on-premises?
    - If using VSTS, provide the account name, team project name, build definition name/build number: 
foeewni; rubik; BUILDTEST_DW_DB_ODS_Build_MASTER / Build 1185

- Agent - Hosted or Private: 
    Hosted VS2017

## Issue Description

The Azure SQL Database Deployment task is failing with a TLS error. It looks like this should be fixed by #6905 - but it's been 20 hours now and still failings. When will this get deployed - or how do I force an upgrade of the task?

This has broken our CI/CD pipeline entirely and we can't work as a result.

### Error logs
```
2018-04-10T04:05:47.4969688Z ##[section]Starting: Execute Azure SQL : DacpacTask
2018-04-10T04:05:47.4975656Z ==============================================================================
2018-04-10T04:05:47.4976569Z Task         : Azure SQL Database Deployment
2018-04-10T04:05:47.4977350Z Description  : Deploy Azure SQL DB using DACPAC or run scripts using SQLCMD
2018-04-10T04:05:47.4978067Z Version      : 1.1.28
2018-04-10T04:05:47.4978707Z Author       : Microsoft Corporation
2018-04-10T04:05:47.4979460Z Help         : [More Information](https://aka.ms/sqlazuredeployreadme)
2018-04-10T04:05:47.4980317Z ==============================================================================
2018-04-10T04:05:48.7377498Z ##[error]Failed to add TLS 1.2 in current session. Error: 'Exception setting "SecurityProtocol": "The requested security protocol is not supported."'
```

**Comment by rajatagrawal-dev** [comment]
@simplesi The TLS 1.2 error that is shown in the logs should not cause the task to fail, even though it is shown as an error. Please check if there is some other error that is getting reported along side TLS 1.2 error. Add a variable _system.debug_ in your release definition and set its value to _true_. Then queue a release to get more detailed logs.

**Comment by simplesi** [comment]
Thanks @rajatagrawal-dev - you're absolutely right. There is indeed a (hidden) error - would be great for everyone if VSTS didn't flag the TLS warning as the cause of the build failure in bright red!

**Comment by rajatagrawal-dev** [comment]
@simplesi #6905 will fix that. TLS issue will not be flagged as error.

**Comment by abhishek-kumar-mishra** [comment]
We also get the same warning (but in red) and that too while deploying to PaaS instances like App Service and Azure SQL. What exactly does this reflect? Is latest TLS not configured in App Service and Azure SQL on the Azure infrastructure?

**Comment by rajatagrawal-dev** [comment]
@abhishek-kumar-mishra Till the fix is not deployed, please ignore this error. I'll update issues #6891 and #6895 once the fix has been deployed.
If you see any TLS related error post that, it probably means that your agent and the Azure service are not able to find a common TLS protocol to communicate with each other. You will need to install some security updates on your agent. No changes will be required by you to be done on your Azure services.

**Comment by abhishek-kumar-mishra** [comment]
I hope we don't need to do any changes as we use Hosted VS2017 agents.

**Comment by rajatagrawal-dev** [comment]
That should be correct. We have already updated hosted agents to use TLS 1.2 by default.

**Comment by RichieBzzzt** [comment]
Hi,

we're still seeing this issue when deploying Azure SQL ARM templates on the Hosted VS2017 Agents. 
![image](https://user-images.githubusercontent.com/26192003/38810570-12155d9e-417f-11e8-8976-860a5801c71e.png)

It's not breaking anything, but thought you might want to know.

**Comment by rajatagrawal-dev** [comment]
@RichieBzzzt Can you share your VSTS account name and also the debug logs of this release. If you don't want to post logs here, you can send the requested info to raagra [AT] microsoft [dot] com.

**Comment by bstoop-github** [comment]
We experience similar issues:

Failed to add TLS 1.2 in current session. Error: 'Exception setting "SecurityProtocol": "The requested security protocol is not supported."'
--
  | Failed to add TLS 1.2 in current session. Error: 'Exception setting "SecurityProtocol": "The requested security protocol is not supported."'
  | Failed to add TLS 1.2 in current session. Error: 'Exception setting "SecurityProtocol": "The requested security protocol is not supported."'
  | Failed to add TLS 1.2 in current session. Error: 'Exception setting "SecurityProtocol": "The requested security protocol is not supported."'
  | Failed to add TLS 1.2 in current session. Error: 'Exception setting "SecurityProtocol": "The requested security protocol is not supported."'
  | Failed to add TLS 1.2 in current session. Error: 'Exception setting "SecurityProtocol": "The requested security protocol is not supported."'

Seems to happen while uploading file to KUDU using powershell..

**Comment by rajatagrawal-dev** [comment]
@bstoop-github Can you share the name of your account? Also, can look at the release logs and check the version of the task (I assume you are using Azure PowerShell task) the releases are using?

**Comment by RichieBzzzt** [comment]
@rajatagrawal-dev Sent. Sorry I mis-spelt your name in the email. Apologies!

**Comment by bstoop-github** [comment]
Name of the VSTS account is : https://kennr.vssps.visualstudio.com
Logs are included in this mail.

Version of the task:

2018-04-11T14:27:53.3594489Z Task : Azure PowerShell
2018-04-11T14:27:53.3595051Z Description : Run a PowerShell script within an Azure environment
2018-04-11T14:27:53.3595603Z Version : 2.0.10

________________________________
Van: Richie Lee <notifications@github.com>
Verzonden: dinsdag 17 april 2018 10:38
Aan: Microsoft/vsts-tasks
CC: bstoop-github; Mention
Onderwerp: Re: [Microsoft/vsts-tasks] TLS 1.2 Error on Azure SQL DB Task (#6925)


@rajatagrawal-dev<https://github.com/rajatagrawal-dev> Sent. Sorry I mis-spelt your name in the email. Apologies!

**Comment by rajatagrawal-dev** [comment]
@bstoop-github We just made a fix and expect that your next release will pick up Azure PowerShell task version **2.0.11**. Let me know if that fixes the issue.

@RichieBzzzt Sorry but I did not receive that mail. Can you comment your account name and the Azure SQL deployment task version that your releases are using here.
